/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    /** Health check */
    get: operations["getHealth"];
  };
  "/auth/login": {
    /** Login with email/password */
    post: operations["login"];
  };
  "/me": {
    /** Get current user profile */
    get: operations["getMe"];
  };
  "/me/features": {
    /** Get feature flags for current user scope */
    get: operations["getMyFeatures"];
  };
  "/patients": {
    /** Search patients */
    get: operations["listPatients"];
    /** Register a new patient */
    post: operations["createPatient"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    User: {
      id?: string;
      email?: string;
      name?: string;
      tenantId?: string;
    };
    CreatePatientDto: {
      name: string;
      /** Format: date */
      dob: string;
      /** @enum {string} */
      gender: "male" | "female" | "other";
      phone?: string;
    };
    Patient: components["schemas"]["CreatePatientDto"] & {
      id?: string;
      mrn?: string;
      /** Format: date-time */
      createdAt?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Health check */
  getHealth: {
    responses: {
      /** @description Service is healthy */
      200: {
        content: {
          "application/json": {
            /** @example ok */
            status?: string;
          };
        };
      };
    };
  };
  /** Login with email/password */
  login: {
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email: string;
          password: string;
        };
      };
    };
    responses: {
      /** @description Login successful */
      200: {
        content: {
          "application/json": {
            accessToken?: string;
          };
        };
      };
    };
  };
  /** Get current user profile */
  getMe: {
    responses: {
      /** @description User profile */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  /** Get feature flags for current user scope */
  getMyFeatures: {
    responses: {
      /** @description Feature flags map */
      200: {
        content: {
          "application/json": {
            [key: string]: boolean;
          };
        };
      };
    };
  };
  /** Search patients */
  listPatients: {
    parameters: {
      query?: {
        query?: string;
        page?: number;
      };
    };
    responses: {
      /** @description List of patients */
      200: {
        content: {
          "application/json": {
            data?: components["schemas"]["Patient"][];
            total?: number;
          };
        };
      };
    };
  };
  /** Register a new patient */
  createPatient: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePatientDto"];
      };
    };
    responses: {
      /** @description Patient created */
      201: {
        content: {
          "application/json": components["schemas"]["Patient"];
        };
      };
    };
  };
}
